### PR TITLE
Support Chinese time (follows up #30)

### PR DESCRIPTION
**Pull request by RexSkz**
This PR follows up #30 with some extra Chinese phrases added.

The first commit is the rebase, and the next commit is mine.

### CODE REVIEW

**Review by olebedev — APPROVED** [review]
LGTM 👍 

However, I can't reason about the Chinese language correctness here, would you be willing to add yourself as an owner of this set of rules, like:

```diff
diff --git a/CODEOWNERS b/CODEOWNERS
new file mode 100644
index 0000000..778dbbf
--- /dev/null
+++ b/CODEOWNERS
@@ -0,0 +1,3 @@
+* @olebedev
+/rules/zh/ @RexSkz
+
```

**Comment by RexSkz** [comment]
Sure!

**Comment by olebedev** [comment]
> Sure!

@RexSkz, awesome! Let me know then the patch above is applied, I’ll merge the PR straight after.

Best,
Oleg

**Comment by RexSkz** [comment]
@olebedev Patch applied, please have a look~

**Comment by olebedev** [comment]
Hey @RexSkz, thanks for that. I am adding you as collaborator to the repository as long as you now own the Chinese language version.

**Comment by RexSkz** [comment]
I'm glad to help :)

**Comment by quxiaolong1504** [comment]
That's awesome, someone actually fixed the test after half a year!

**Pull request merged**
