### PR TITLE
update SlashDMY regex to more reliably match on dd/mm/yyyy dates

### PR DESCRIPTION
**Pull request by cpalsulich**
Fix for https://github.com/olebedev/when/issues/36

### CODE REVIEW

**Review by olebedev — CHANGES_REQUESTED** [review]
Hi @cpalsulich,

Thank you for your PR. I appreciate your effort in this matter. However, I cannot accept the proposed change as it goes against the original concept of the `slash_dmy` rule. To gain further insight into this decision, kindly refer to [this](https://github.com/olebedev/when/issues/36#issuecomment-1566315948) comment.

Please feel free to open another PR or issue when you believe it is suitable.

Best regards,
Oleg

**Comment by cpalsulich** [comment]
Hi @olebedev, can you point me to the concept of the `slash_dmy` rule? As I understand the concept from context, it should match/return true on dates roughly in the dd/mm/yyyy format. If you disregard [my created issue](https://github.com/olebedev/when/issues/36) referencing mm/dd/yyyy dates, something like 19/19/19 (which isn't a valid date in either format) would match the regex and cause a panic. When trying to parse natural language, we little to no control over what the contents of the string are and so it makes sense to me to try to be as restrictive as possible. Just to be clear I don't care at all about parsing mm/dd/yyyy dates correctly. I do care as a user of this library that my program continues to run. That was my only intention in submitting this PR.

**Comment by olebedev** [comment]
Hey @cpalsulich,

> As I understand the concept from context, it should match/return true on dates roughly in the dd/mm/yyyy format.

Yup, this is correct understanding, except what the rule returns, but these are technical details that we can skip for now.


> Just to be clear I don't care at all about parsing mm/dd/yyyy dates correctly. I do care as a user of this library that my program continues to run. That was my only intention in submitting this PR.

I looked at the PR once again and I have to apologies I misread it initially, your addition is to fix the panic situation for the dates that are not real possible dates as `dd/mm/yyyy` but any combo of `nn/nn/nnnn`. The change makes perfect sense to me now, again, sorry for the initial rejection of the change.

**Review by olebedev — APPROVED** [review]
LGTM 👍 

Thanks!

**Pull request merged**
