### PR TITLE
Support Chinese time

### PR DESCRIPTION
**Pull request by quxiaolong1504**
#### AfterTime
`后天中午`
`下月6号`

#### Weekday
`下周三` `下下周二`

### CODE REVIEW

**Comment by quxiaolong1504** [comment]
@olebedev  here

**Comment by olebedev** [comment]
Hey @quxiaolong1504,

Thank you for your contribution. However, I am not sure if I am qualified to verify the language-specific stuff here.  From the perspective of the code structure and testing it looks good to me 👍 

Before merging, I would like to see some test results. Can you rebase of this https://github.com/olebedev/when/pull/31 so we can see in it your PR?

**Comment by quxiaolong1504** [comment]
ok~ rebase done #31 done

**Comment by quxiaolong1504** [comment]
Hello @olebedev  i rebase #31 . But the test was not triggered.

**Comment by olebedev** [comment]
No idea why it hasn't been triggered. I checked out the branch and got an error:

```
λ go test ./...
?   	github.com/olebedev/when	[no test files]
?   	github.com/olebedev/when/rules	[no test files]
ok  	github.com/olebedev/when/rules/br	0.724s
ok  	github.com/olebedev/when/rules/common	0.522s
ok  	github.com/olebedev/when/rules/en	1.318s
ok  	github.com/olebedev/when/rules/ru	1.029s
--- FAIL: TestExactMonthDate (0.00s)
    require.go:157: 
        	Error Trace:	zh_test.go:24
        	            				exact_month_test.go:33
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 3
        	Test:       	TestExactMonthDate
        	Messages:   	[zh.ExactMonthDate] index #6
FAIL
FAIL	github.com/olebedev/when/rules/zh	1.517s
FAIL
```

**Comment by 5idu** [comment]
How is the issue going, this function is really great, looking forward to it!

**Comment by olebedev** [comment]
@quxiaolong1504, friendly ping

**Comment by olebedev** [comment]
Hello @5idu,

I noticed your interest in this feature. Would you be willing to take over from @quxiaolong1504 and work on it? I believe this is the only remaining step needed to complete it. That would be fantastic while we wait for @quxiaolong1504.

Best regards,
Oleg

**Comment by RexSkz** [comment]
I'm also interested in this feature. I just found that test cases are triggered, but there's a bug in the code:

image

The source "十一月一日" (Nov 1st) is parsed to "一月一日" (Jan 1st), and the `index` is also wrong.

I'd like to help fixing it~

**Comment by olebedev** [comment]
Hey @quxiaolong1504, do you think this one is still relevant, given we already have most of the change landed in this https://github.com/olebedev/when/pull/39 PR? Feel free to close it, if you think it's appropriate :)

**Pull request closed without merging**
